/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PersonManager;

/**
 *
 * @author rutugawad
 */
public class ViewPerson_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPerson_JPanel
     */
    public ViewPerson_JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SSN_Text = new javax.swing.JTextField();
        SSN_Label = new javax.swing.JLabel();
        HomeUnitNumber_Text = new javax.swing.JTextField();
        HomeStreetName_Label = new javax.swing.JLabel();
        HomeState_Text = new javax.swing.JTextField();
        HomeCity_Label = new javax.swing.JLabel();
        HomePhoneNumber_Text = new javax.swing.JTextField();
        HomeZIP_Label = new javax.swing.JLabel();
        HomeStreetName_Text = new javax.swing.JTextField();
        WorkStreetName_Label = new javax.swing.JLabel();
        HomeCity_Text = new javax.swing.JTextField();
        WorkCity_Label = new javax.swing.JLabel();
        HomeZIP_Text = new javax.swing.JTextField();
        WorkUnitNumber_Text = new javax.swing.JTextField();
        WorkZIP_Label = new javax.swing.JLabel();
        HomeAddress_Label = new javax.swing.JLabel();
        WorkState_Text = new javax.swing.JTextField();
        WorkAddress_Label = new javax.swing.JLabel();
        WorkPhoneNumber_Text = new javax.swing.JTextField();
        WorkStreetName_Text = new javax.swing.JTextField();
        Update_Button = new javax.swing.JButton();
        WorkCity_Text = new javax.swing.JTextField();
        WorkZIP_Text = new javax.swing.JTextField();
        LastName_Label = new javax.swing.JLabel();
        Age_Label = new javax.swing.JLabel();
        HomeUnitNumner_Label = new javax.swing.JLabel();
        HomeState_Label = new javax.swing.JLabel();
        HomePhoneNumber_Label = new javax.swing.JLabel();
        PersonProfile_Title = new javax.swing.JLabel();
        FirstName_Text = new javax.swing.JTextField();
        WorkUnitNumber_Label = new javax.swing.JLabel();
        WorkState_Label = new javax.swing.JLabel();
        LastName_Text = new javax.swing.JTextField();
        WorkPhoneNumber_Label = new javax.swing.JLabel();
        Age_Text = new javax.swing.JTextField();
        FirstName_Label = new javax.swing.JLabel();

        SSN_Label.setText("SSN");

        HomeStreetName_Label.setText("Street Name");

        HomeCity_Label.setText("City");

        HomeZIP_Label.setText("ZIP Code");

        HomeStreetName_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeStreetName_TextActionPerformed(evt);
            }
        });

        WorkStreetName_Label.setText("Street Name");

        WorkCity_Label.setText("City");

        WorkZIP_Label.setText("ZIP Code");

        HomeAddress_Label.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        HomeAddress_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeAddress_Label.setText("Home Address");

        WorkState_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkState_TextActionPerformed(evt);
            }
        });

        WorkAddress_Label.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        WorkAddress_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkAddress_Label.setText("Work Address");

        Update_Button.setText("Update");

        WorkCity_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkCity_TextActionPerformed(evt);
            }
        });

        LastName_Label.setText("Last Name");

        Age_Label.setText("Age");

        HomeUnitNumner_Label.setText("Unit Number");

        HomeState_Label.setText("State");

        HomePhoneNumber_Label.setText("Phone Number");

        PersonProfile_Title.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        PersonProfile_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonProfile_Title.setText("Person Profile");

        WorkUnitNumber_Label.setText("Unit Number");

        WorkState_Label.setText("State");

        WorkPhoneNumber_Label.setText("Phone Number");

        Age_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_TextActionPerformed(evt);
            }
        });

        FirstName_Label.setText("First Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PersonProfile_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeAddress_Label)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstName_Label)
                                    .addComponent(SSN_Label)
                                    .addComponent(HomeStreetName_Label)
                                    .addComponent(HomeCity_Label)
                                    .addComponent(HomeZIP_Label)
                                    .addComponent(WorkStreetName_Label)
                                    .addComponent(WorkCity_Label)
                                    .addComponent(WorkZIP_Label)
                                    .addComponent(WorkAddress_Label))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HomeZIP_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WorkStreetName_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WorkCity_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WorkZIP_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HomeCity_Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SSN_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HomeStreetName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HomeUnitNumner_Label)
                                    .addComponent(HomeState_Label)
                                    .addComponent(HomePhoneNumber_Label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LastName_Label)
                                                        .addComponent(Age_Label))
                                                    .addGap(57, 57, 57))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(WorkUnitNumber_Label)
                                                    .addGap(47, 47, 47)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(WorkState_Label)
                                                    .addComponent(WorkPhoneNumber_Label))
                                                .addGap(34, 34, 34)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(WorkState_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                            .addComponent(WorkUnitNumber_Text)
                                            .addComponent(Age_Text)
                                            .addComponent(LastName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HomeUnitNumber_Text)
                                            .addComponent(HomeState_Text)
                                            .addComponent(HomePhoneNumber_Text)
                                            .addComponent(WorkPhoneNumber_Text))))))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(Update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(PersonProfile_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName_Label)
                    .addComponent(FirstName_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSN_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Age_Label)
                    .addComponent(SSN_Label))
                .addGap(53, 53, 53)
                .addComponent(HomeAddress_Label)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeUnitNumber_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeStreetName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeUnitNumner_Label)
                    .addComponent(HomeStreetName_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeState_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeCity_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeState_Label)
                    .addComponent(HomeCity_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomePhoneNumber_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeZIP_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomePhoneNumber_Label)
                    .addComponent(HomeZIP_Label))
                .addGap(59, 59, 59)
                .addComponent(WorkAddress_Label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkUnitNumber_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkStreetName_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkUnitNumber_Label)
                    .addComponent(WorkStreetName_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkState_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkCity_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkState_Label)
                    .addComponent(WorkCity_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WorkPhoneNumber_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkZIP_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkPhoneNumber_Label)
                    .addComponent(WorkZIP_Label))
                .addGap(49, 49, 49)
                .addComponent(Update_Button)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HomeStreetName_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeStreetName_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeStreetName_TextActionPerformed

    private void WorkState_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkState_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkState_TextActionPerformed

    private void WorkCity_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkCity_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkCity_TextActionPerformed

    private void Age_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_TextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age_Label;
    private javax.swing.JTextField Age_Text;
    private javax.swing.JLabel FirstName_Label;
    private javax.swing.JTextField FirstName_Text;
    private javax.swing.JLabel HomeAddress_Label;
    private javax.swing.JLabel HomeCity_Label;
    private javax.swing.JTextField HomeCity_Text;
    private javax.swing.JLabel HomePhoneNumber_Label;
    private javax.swing.JTextField HomePhoneNumber_Text;
    private javax.swing.JLabel HomeState_Label;
    private javax.swing.JTextField HomeState_Text;
    private javax.swing.JLabel HomeStreetName_Label;
    private javax.swing.JTextField HomeStreetName_Text;
    private javax.swing.JTextField HomeUnitNumber_Text;
    private javax.swing.JLabel HomeUnitNumner_Label;
    private javax.swing.JLabel HomeZIP_Label;
    private javax.swing.JTextField HomeZIP_Text;
    private javax.swing.JLabel LastName_Label;
    private javax.swing.JTextField LastName_Text;
    private javax.swing.JLabel PersonProfile_Title;
    private javax.swing.JLabel SSN_Label;
    private javax.swing.JTextField SSN_Text;
    private javax.swing.JButton Update_Button;
    private javax.swing.JLabel WorkAddress_Label;
    private javax.swing.JLabel WorkCity_Label;
    private javax.swing.JTextField WorkCity_Text;
    private javax.swing.JLabel WorkPhoneNumber_Label;
    private javax.swing.JTextField WorkPhoneNumber_Text;
    private javax.swing.JLabel WorkState_Label;
    private javax.swing.JTextField WorkState_Text;
    private javax.swing.JLabel WorkStreetName_Label;
    private javax.swing.JTextField WorkStreetName_Text;
    private javax.swing.JLabel WorkUnitNumber_Label;
    private javax.swing.JTextField WorkUnitNumber_Text;
    private javax.swing.JLabel WorkZIP_Label;
    private javax.swing.JTextField WorkZIP_Text;
    // End of variables declaration//GEN-END:variables
}
